services:
  guestbook:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - /Users/gyuminhwangbo/data:/data
    environment:
      - DATABASE_URL=sqlite:////data/guestbook.db
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
