oauth:
  providers:
    kakao:
      client-id: your-kakao-client-id
      client-secret: your-kakao-client-secret
      redirect-uri: http://localhost:8080/login/oauth2/code/kakao
      scopes:
        - account_email

    naver:
      client-id: your-naver-client-id
      client-secret: your-naver-client-secret
      redirect-uri: http://localhost:8080/login/oauth2/code/naver
      scopes:
        - name
        - email
        - profile_image
        - age

    google:
      token-revocation-uri: https://oauth2.googleapis.com/revoke
      client-id: your-google-client-id
      client-secret: your-google-client-secret
      redirect-uri: http://localhost:8080/login/oauth2/code/google
      token-path: https://oauth2.googleapis.com/token
      code-path: https://accounts.google.com/o/oauth2/v2/auth
      user-info-path: https://www.googleapis.com/oauth2/v3/userinfo
      scopes:
        - openid
        - email
        - profile