
spring:
  config:
    import:
      - optional:aws-secretsmanager:personal/beta
      - classpath:application-kafka.yaml
      - classpath:application-redis.yaml
      - classpath:application-mysql.yaml
      - classpath:application-common.yaml
  cloud:
    aws:
      region:
        static: ap-northeast-2
      credentials:
        profile:
          name: default
      secretsmanager:
        enabled: true
        fail-fast: false
management:
  endpoints:
    web:
      exposure:
        include: prometheus,metrics,health,info
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
  metrics:
    tags:
      application: monitoring-service
      environment: local
  prometheus:
    metrics:
      export:
        enabled: true


