spring:
  batch:
    job:
      enabled: false
  application:
    name: client
  quartz:
    job-store-type: memory
    auto-startup: true
  thymeleaf:
    enabled: true
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
  web:
    resources:
      static-locations: classpath:/static/
      cache:
        period: 0
  output:
    ansi:
      enabled: ALWAYS
  cloud:
    aws:
      region:
        static: ap-northeast-2
      credentials:
        profile:
          name: default
      secretsmanager:
        enabled: true
        fail-fast: false

# AI 설정s
ai:
  provider: ollama  # 'openai' 또는 'ollama' 선택

# OpenAI 설정 (ai.provider=openai 일 때 사용)
openai:
  api:
    key: ${OPENAI_API_KEY:}

# Ollama 설정 (ai.provider=ollama 일 때 사용)
ollama:
  url: http://127.0.0.1:11434
  model: gemma3

arxiv:
  retry:
    max-retries: 3
    initial-delay-ms: 2000
    rate-limit-multiplier: 2
    exponential-backoff: true

redis:
  host: localhost
  port: 6379
  stream:
    summary: paper:summary:stream
    group: paper-summary-group
    # 이벤트 타입별 개별 스트림 (단순화)
    events:
      paper-search-and-store: domain:events:paper-search-and-store
      summary: domain:events:summary
      group: event-handlers
    consumer:
      name: paper-summary-consumer-1
      threads: 50

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  model-and-view-allowed: true

oauth:
  enable-providers: true
  providers:
    kakao:
      scopes: profile_nickname, account_email

server:
  port: 7070
