spring:
  profiles:
    active: local
  application:
    name: orchestrator
  config:
    import:
      - classpath:application-kafka.yaml
      - classpath:application-mysql.yaml

# Saga Configuration
saga:
  # 모든 응답을 받을 단일 토픽
  response-topic: saga-response
  # Consumer Group ID
  consumer-group: saga-orchestrator-group

# Server Configuration
server:
  port: 9090

# Springdoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    doc-expansion: none

# Logging
logging:
  level:
    org.ghkdqhrbals.orchestrator.saga: DEBUG
    org.springframework.kafka: INFO
    org.hibernate.SQL: DEBUG


